name: places
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  intl: ^0.18.0
  provider: ^6.0.3
  http: ^0.13.4

  # firebase_auth: ^4.2.2
  # firebase_storage: ^11.0.10
  # # firebase_messaging: ^14.2.1
  # firebase_core: ^2.4.1
  # cloud_firestore: ^4.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - res/
    - res/icons/
    - res/icons/empty_pages/
    - res/icons/menu/
    - res/icons/other/
    - res/icons/tutorial/
    - res/icons/catalog/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/roboto/Roboto-Italic.ttf
